# Generated by Django 5.0.7 on 2024-07-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipes",
            fields=[
                ("recipe_id", models.AutoField(primary_key=True, serialize=False)),
                ("recipe_image", models.ImageField(upload_to="images/")),
                ("recipe_description", models.CharField(max_length=10000)),
                ("recipe_name", models.CharField(max_length=100)),
                ("ingredients", models.JSONField(blank=True, default=list)),
                ("preparation_time", models.JSONField(blank=True, default=list)),
                ("instruction", models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
