# Generated by Django 5.0.7 on 2024-07-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="ingredients",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="instruction",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="preparation_time",
            field=models.CharField(max_length=100),
        ),
    ]
